# Site
repository: tyler-macinnis/tyler-macinnis.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal Info
name: Tyler MacInnis
title: Computer Science Student
email: thmac2017@gmail.com
website: https://tyler-macinnis.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Tyler_MacInnis
github_username: tyler-macinnis
instagram_username: tyler_macinnis1
linkedin_username: tyler-macinnis-compsci

# Additional icon links
additional_links:

# About Section
about_profile_image: images/profile.jpg
about_content: | #Allows new lines to include paragraphs
  Hi, my name is Tyler and I'm a Computer Science student at Clemson University. I aspire to use my computing skills to help make the world a better place. I have a strong work ethic and passion for using my talents. In my spare time, I like to play Dungeons & Dragons, as both a player and a dungeon master.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Population Dynamics - Virtual Reality Population Simulator
        description: | # this will include new lines to allow paragraphs
          Created a educational population simulator targetted towards high school students that runs as a VR application.
    
      - layout: top-middle
        title: ClemBot Contributor
        link: github.com/ClemsonCPSC-Discord/ClemBot
        # link_text: Project Website
        additional_links:
          - title:  ClemsonCPSC-Discord/ClemBot
            icon: fab fa-github
            url: github.com/ClemsonCPSC-Discord/ClemBot
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a Discord Bot for the Clemson Computer Science Discord Server.
        description: | # this will include new lines to allow paragraphs
          I started contributing to this project in September of 2020 as a way of learning python and git.
          It continues to grow thanks to the efforts Clemson Students and Alumni.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Atlas Copco
        # link: 
        # link_text: 
        sub_title: Embedded Systems Intern
        caption: June 2022 - August 2022
        # quote: >
          # Quote
        description: | # this will include new lines to allow paragraphs
            - Added unit testing and software validation methods
            - Improved legacy code while ensuring functionality
            - Created through documentation on testing procedures for the future
     
      - layout: left
        title: DHL Supply Chain
        # link: 
        # link_text: 
        sub_title: Loader/Unloader
        caption: June 2021 - August 2021
        # quote: >
          # Quote
        description: | # this will include new lines to allow paragraphs
            - Unloaded product deliveries
            - Maintained cleanliness of the warehouse
            - Assessed inventory accuracy
            
      - layout: left
        title: Harris Teeter Grocery Store
        # link: 
        # link_text: 
        sub_title: Cashier and Personal Shopper
        caption: November 2019 - January 2020
        # quote: >
          # Quote
        description: | # this will include new lines to allow paragraphs
            - Handled monetary transactions with accuracy and proficiency
            - Provided world-class customer service by answering questions and assisting customers
            - Used situational awareness and grocery store knowledge to find product substitutions as a personal shopper
    
      - layout: left
        title: SCDOT York Maintenance
        # link: 
        # link_text: 
        sub_title: Assistant Geodetic Technician
        caption: May 2019 - August 2019
        # quote: >
          # Quote
        description: | # this will include new lines to allow paragraphs
            - Designed a future-ready Excel Spreadsheet for assessing work crew progress
            - Updated the system for maintaining current SDS and developed a system for printing compliant safety labels
            - Improved the methods for recording and tracking PPE (Personal Protective Equipment)

      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Clemson University
        link: https://www.clemson.edu/
        caption: December 2022
        sub_title: Bachelor of Science in Computer Science
        # quote: >
          # Quote
        description: | # this will include new lines to allow paragraphs
          Currently studying software development and computer systems organization.

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Microsoft Excel Certified
      - Tools: Git, Windows, Linux, VSCode, Unity
      - Languages: C/++, Java, Python, Unix
      - Strong understanding of algorithms, data structures, systems analysis, software development, machine learning, and object-oriented programming
      -	Adaptable and flexible
      -	Collaboration and teamwork
      -	Organization and time management
      -	Excellent communicator
      -	Strong work ethic

  - title: Awards
    layout: text
    content: |
      - Eagle Scout - October 2014
      - Scottish Rite JROTC Medal for Scholastic Excellence and Americanism - May 2015

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computing and software development some of my other interests and hobbies are:
      - Tabletop Roleplaying Games, particularly Dungeons & Dragons 5e
      - Reading
      - Running
      - Hiking

    # INDENT Look at this cool image  
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
